### ISSUE TITLE
怎么使用可以描述一下吗

### ISSUE THREAD

**Issue by ghost** [yinyangxu/docidx#1]
怎么使用可以描述一下吗

**Comment by yinyangxu** [comment]
可以看下readme哈

$ virtualenv --system-site-packages dev_env
$ . dev_env/bin/activate
(dev_env)$ pip install -r requirements.txt
(dev_env)$ bash create.sh
(dev_env)$ python wsgi.py
$ firefox 'http://127.0.0.1:9090'

**Comment by ghost** [comment]
这个是解决,搜索全局的不显示问题吗

**Comment by yinyangxu** [comment]
早年gitlab的搜索功能还比较弱，后台的实现就是一个select like语句，所以只能搜一些项目的名称啥的，无法对文档内容进行搜索，于是开发了这么个小工具，后台直接读取git repo源码内的mark down文档内容进行建立索引，在web端提供搜索服务。

**Comment by yinyangxu** [comment]
> 这个是解决,搜索全局的不显示问题吗

是的，这个小功能是全局对所有项目搜索的，现在gitlab已经提供项目内搜索功能，当时好像项目内代码文档搜索都没有。

**Comment by ghost** [comment]
这个小工具，需要配置数据库地址吗

**Comment by yinyangxu** [comment]
要的，需要拉取gitlab里公有的git项目路径信息，https://github.com/yinyangxu/docidx/blob/master/add_doc.py#L119

**Comment by ghost** [comment]
gitlab-ce默认装的
DATABASE = parser.get('db', 'dbname')
HOST = parser.get('db', 'host')
USER = parser.get('db', 'user')
PASSWORD = parser.get('db', 'password')
怎么填写阿。

**Comment by yinyangxu** [comment]
后台肯定有个数据库的，去看下gitlab源码的配置信息，连接串信息你可以根据实际情况修改，也可以自己实现，最终目的就是为了从数据库捞取git repo的path信息。

**Comment by ghost** [comment]
DATABASE = parser.get('db', 'gitlabhq_production')
HOST = parser.get('db', '127.0.0.1')
USER = parser.get('db', 'gitlab-psql')
PASSWORD = parser.get('db', '')

db我该如何更改报错执行create.sh
/root/dev_env/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "add_doc.py", line 21, in <module>
    DATABASE = parser.get('db', 'gitlabhq_production')
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'db'

**Comment by yinyangxu** [comment]
https://github.com/yinyangxu/docidx/blob/master/docidx.conf.example 这个配置文件配置一下，cp docidx.conf.example docidx.conf

**Comment by ghost** [comment]
(dev_env) [root@gitlab docidx]# bash create.sh
/root/dev_env/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "add_doc.py", line 130, in <module>
    main()
  File "add_doc.py", line 119, in main
    cur.execute("SELECT n.path, p.path FROM namespaces as n, projects as p WHERE n.id = p.namespace_id AND p.public = true")
psycopg2.ProgrammingError: column p.public does not exist
LINE 1: ... n, projects as p WHERE n.id = p.namespace_id AND p.public =...

**Comment by yinyangxu** [comment]
这个代码还是四年前的，四年过去了gitlab应该有不少较大的变动，估计要你自己hack一下了，或者知道原理后得写一个，表结构也肯定有更改，这个sql就是获取公有项目的namespace和项目路径。
